config/routes.rb
WebCal::Application.routes.draw do
  resources :timeperiods

  match '/calendars(/:year(/:month))' => 'calendars#index', 
  :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :calendars
  resources :alternatives
  
  match 'users/profile' => 'users#profile', :as=>:user_profile
  match 'users/find_friends' => 'users#find_friends', :as => :user_find_friends
  match 'users/find_events' => 'users#find_events', :as => :user_find_events
  match 'users/friends' => 'users#friends', :as => :user_friends
  
  resources :friendships do
	collection do
		get :friend_requests, :users_list
		post :approve, :ignore, :users_list
  	end
  end
  
  resources :events do
    collection do
      get :invite_friend, :show_calendar
      post :add_timeperiods
    end
  end

  resources :posts

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
                                      :registrations => 'registrations',
                                      :sessions => 'sessions'}

  root :to => 'friendships#users_list' 

end

app/models/user.rb
class User < ActiveRecord::Base
  #validates_format_of :zipcode, :with => /^\d{5}(-\d{4})?$/
  devise :omniauthable
  require 'open-uri'
  require 'json'

  validate :first_name, :presence => true
  validate :last_name, :presence => true

  has_many :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"

  has_many :direct_friends, :through => :friendships, :conditions => "approved = true", :source => :friend
  has_many :inverse_friends, :through => :inverse_friendships, :conditions => "approved = true", :source => :user

  has_many :pending_friends, :through => :friendships, :conditions => "approved = false and ignored = false", :foreign_key => "user_id", :source => :friend
  has_many :requested_friends, :through => :inverse_friendships, :foreign_key => "friend_id", :conditions => "approved = false and ignored = false", :source => :user

  has_many :calendars

  has_many :events
  has_and_belongs_to_many :invited_events, :class_name => "Event"

  has_many :posts
  has_many :timeperiods

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :zipcode, :city, :state, :friends,
    :first_name, :last_name, :provider, :uid, :image_url, :fbonly, :name, :google_id, :is_fb?, :is_google?, :token
  # attr_accessible :title, :body
  def is_fb?
    return self.uid != nil
  end

  def is_google?
    return self.token != nil
  end

  def set_default_picture
    user = self
    unless user.image_url
      user.image_url = 'default_fb_pic.jpg'
    end
    user.save
  end

  def find_friends
    user = self
    token = user.fb_token
    id = user.uid

    request_url = 'https://graph.facebook.com/'+id+'/friends?access_token='+token
    logger.info request_url

    body = open(request_url).read
    parsed_json = JSON(body)

    parsed_json["data"].each do |data|
      uid = data["id"]

      tempuser = User.where(:uid => uid.to_s()).first
      unless tempuser
        image_url = "http://graph.facebook.com/"+uid+"/picture?type=large"
        logger.info "FRIENDIMAGE" + image_url

        name = data["name"]
        tempuser = User.new(:name => name,
                            :uid => uid,
                            :email=> name + "@facebook.com",
                            :image_url => image_url,
                            :password=>Devise.friendly_token[0,20],
                            :fbonly => true
                            )
        tempuser.save
        tempuser.set_default_picture
      end

      friendship = Friendship.new
      friendship.make_new(self, tempuser, true)
    end
  end

  def find_events
    user = self
    request_url = 'https://www.googleapis.com/calendar/v3/users/me/calendarList?access_token='+user.token
    body = open(request_url).read
    parsedjson = JSON(body)

    calendar_types = Array.new

    parsedjson["items"].each do |item|
      calendar_types.push(item["id"])
      logger.info id
    end

    calendar_types.each do |cal|
      begin
        request_url = 'https://www.googleapis.com/calendar/v3/calendars/'+cal+'/events?access_token='+user.token
        logger.info request_url

        body = open(request_url).read
      rescue
        next
      end

      parsedjson = JSON(body)

      if parsedjson["items"]
        parsedjson["items"].each do |event|
          unless Event.where(:google_id => event["id"], :user_id => user.id).first
            if event["start"] && event["end"] && event["start"]["dateTime"] && event["end"]["dateTime"]
              unless Time.parse(event["end"]["dateTime"].to_s) < Time.now
                new_event = Event.new(:start_at => event["start"]["dateTime"],
                                      :title => event["summary"],
                                      :end_at => event["end"]["dateTime"],
                                      :google_id => event["id"])
                new_event.user_id = user.id
                new_event.save
              end
            end
          end
        end
      end
    end
  end

  def friends
    direct_friends | inverse_friends
  end

  def is_friends?(user)
    return self.friends.include?(user)
  end

  def is_pending_friends?(user)
    return self.pending_friends.include?(user) || self.requested_friends.include?(user)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource)
    user = User.where(:uid => auth.uid).first

    #for google users who are already logged in
    if signed_in_resource
      user = signed_in_resource
      user.uid = auth.uid
      user.fb_token = auth.credentials.token
      user.save

      #delete users who might have logged in with both before merging
      User.where(:uid => auth.uid).each do |u|
        unless u.is_google? && u.is_fb?
          u.destroy
        end
      end

      user.delay.find_friends

      return user
    end

    email = auth.info.email
    unless email
      email = auth.info.nickname + '@facebook.com'
    end

    unless user
      image_url = "http://graph.facebook.com/"+auth.uid+"/picture?type=large"
      user = User.create(:name => auth.info.name,
                         :provider => auth.provider,
                         :uid => auth.uid,
                         :email=> email,
                         :image_url => image_url,
                         :password=>Devise.friendly_token[0,20]
                         )
    end

    if user.fbonly = true
      user.name = auth.info.name
      user.email = email
      user.password = Devise.friendly_token[0,20]
      user.save
    end

    user.fb_token = auth.credentials.token
    user.save

    user.delay.find_friends

    user
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource)
    data = access_token.info
    tokens = access_token.credentials
    logger.info access_token

    email = data.email

    user = User.where(:google_id => access_token.uid).first

    #for facebook users who are already logged in
    if signed_in_resource
      user = signed_in_resource
      user.refresh_token = tokens.refresh_token
      user.token = tokens.token
      user.google_id = access_token.uid
      user.save

      #delete users who might have logged in with both before merging
      User.where(:google_id => user.google_id).each do |u|
        unless u.is_google? && u.is_fb?
          u.destroy
        end
      end

      user.delay.find_events

      return user
    end

    unless user
      user = User.create(:name => data.name,
                         :provider => 'google',
                         :email=> email,
                         :password=>Devise.friendly_token[0,20],
                         :google_id => access_token.uid
                         )
      user.set_default_picture
    end
    user.refresh_token = tokens.refresh_token
    user.token = tokens.token
    user.save

    user.delay.find_events

    user
  end

  def has_requests?
    if self.requested_friends.count == 0
      return false
    end
    return true
  end

  def self.search(name)
    if name
      find(:all, :order => ['case when lower(name) LIKE '+ "'" +name+ '%' + "' " + 'then 1 else 0 end DESC,' +
                            'case when lower(email) LIKE '+ "'" +name+ '%' + "' " + 'then 1 else 0 end DESC'],
           :conditions => ['lower(name) LIKE ? OR lower(email) LIKE ?', "%#{name}%", "%#{name}%"],
           :limit => 99)
    else
      find(:all, :limit => 99)
    end
  end

  def self.search_friends(name, id)
    if name
      find(:all , :from => '(SELECT * from "users" INNER JOIN "friendships" on "users"."id" = '+
           '"friendships"."friend_id" where "friendships"."user_id" = '+id.to_s()+')  AS "users"',
           :order => ['case when lower(name) LIKE '+ "'" +name+ '%' + "' " + 'then 1 else 0 end DESC,' +
                      'case when lower(email) LIKE '+ "'" +name+ '%' + "' " + 'then 1 else 0 end DESC'],
           :conditions => ['lower(name) LIKE ? OR lower(email) LIKE ?',
                           "%#{name}%", "%#{name}%"],
           :limit => 99)
    else
      find(:all, :from => '(SELECT * from "users" INNER JOIN "friendships" on "users"."id" = '+
           '"friendships"."friend_id" where "friendships"."user_id" = '+id.to_s()+')  AS "users"', :limit => 99)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user
      if @user.sign_in_count < 2
        sign_in @user
        redirect_to alternatives_path
        return
      end
      flash[:warning] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
      if @user
        if @user.sign_in_count < 2
          sign_in @user
          redirect_to alternatives_path
          return
        end
        flash[:warning] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def profile
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to 
    end
  end
  
  def friends
    @users = []
    
    if params[:name]
      @name = params[:name]
      friends = User.search_friends(@name.downcase, current_user.id)
    else 
      friends = current_user.friends
    end

    if params[:event]
      @event = Event.find(params[:event])
    end
    
    @previous_page = true
    @next_page = true
    
    @totalnum = friends.count/25
    
    if params[:page].to_i() > 0
      @page_num = params[:page].to_i()
    else
      @page_num = 0
      @previous_page = false
    end
        
    if @page_num >= @totalnum
      @page_num = @totalnum
      @next_page = false
    end
    
    if friends.first
      @friends = friends[@page_num*25..(@page_num+1)*24] 
    else
      @friends = []
    end
    
  end  

end

app/views/users/_friend_search.html.erb
<%= form_tag(invite_friend_events_path(:event => @event), :remote => true, :method => :get) do %>
	<%= text_field_tag :name, params[:name]%>
	<%= submit_tag "Search for a friend", :name => nil, :class => 'btn btn-success' %>
<% end %>

app/views/users/_friends.html.erb
<% if @friends.count > 0 %>
			<table class = 'table'>
				<th></th>
				<th>Name</th>
				<th>
				<% if @previous_page %>
					<%= link_to "Previous 25", user_friends_path(:page => @page_num-1), :method => :post, :class => 'btn'%>
				<% end %>		
				
				<% if @next_page %>
					<%= link_to "Next 25", user_friends_path(:page => @page_num+1), :method => :post, :class => 'btn' %>
				<% end %></th>
			<% @friends.each do |friend| %>
				<tr>
					<td><%= image_tag(friend.image_url, :class=>'span4')%></td>
					<td><%= friend.name %></td>					
					<% 
					if @event
						 if @event.invited_users.include?(friend)
						 	path = false
							button_title = "Uninvite Friend"
							button_class = 'btn btn-warning'
							form_class = 'uninvite_friend_button'
						else
							path = true
						 	button_title = "Invite Friend"
						 	button_class = 'btn'
						 	form_class = 'invite_friend_button'
						 end 
					else
					 	path = true
					 	button_title = "Invite Friend"
					 	button_class = 'btn'
					 	form_class = 'invite_friend_button'
					end
					 %>
					 
					<td><%= button_to button_title, invite_friend_events_path(:event => @event, :user =>friend.id,:path=>path),
					:remote => true, :method => "get", :class => button_class, :form_class => form_class %></td>
				</tr>
			<%end%>
			</table>
			<div class = 'container-fluid'>
				<div class = 'span7'>
				</div>
				<div class = 'span5'>
				<p>
				<% if @previous_page %>
					<%= link_to "Previous 25", user_friends_path(:page => @page_num-1), :method => :post, :class => 'btn'%>
				<% end %>		
				
				<% if @next_page %>
					<%= link_to "Next 25", user_friends_path(:page => @page_num+1), :method => :post, :class => 'btn' %>
				<% end %>
				</p>
				</div>
			</div>
		<% else %>
		<h2>You don't have any friends. Go make some.</h2>
		Or import your <%= link_to "Facebook friends here", omniauth_authorize_path(current_user, 'facebook'),
			:class => 'zocial facebook', :method => :post, :title => "Import Facebook Friends" %>
		<%end%>

app/views/users/friends.html.erb
	<h4><%= link_to "Find your Facebook friends", omniauth_authorize_path(current_user, 'facebook'),
		:class => 'zocial facebook', :method => :post, :id => 'facebook-import', 
		:title => "Import Facebook Friends" %></h4> <br/>
<div id = 'friend-search'>
	<%= render 'friend_search' %>
</div>	
<div class = 'container-fluid'>
	<div class = 'span8' id = 'friend-div'>
		<%= render 'friends' %>
	</div>
	<div class = 'span4' id = 'update-div' style = "height:500px;overflow:auto">
		<%= render 'events/invite_list' %>
	</div>
</div>

app/views/users/profile.html.erb
<div>
<h2>Hello, <%= @user.name %>!</h2>	<br/>
</div>
<div class = 'container-fluid'>
	<div class = 'span8'>
		<div class = 'container-fluid well'>
			This is your profile.  Here you can 
			<%= link_to "edit your account information", edit_user_registration_path, :class => 'btn btn-success'%>, 
			<%= link_to "change your picture", 'fake#path', :class => 'btn btn-success'%>, and look
			at your upcoming events.  
		</div>
		<div class = 'container-fluid'>
			<div class = 'span6'>
				<%= image_tag(@user.image_url, :class => 'span8')%>
			</div>
			<div class = 'span6'>
					<%= link_to "", user_find_friends_path(:user => current_user.id),
				:class => 'zocial facebook icon', :method => :post, :id => 'facebook-import', 
				:title => "Import Facebook Friends" %>
				<%= link_to "", user_find_events_path(:user => current_user.id),
				:class => 'zocial googleplus icon', :method => :post, :id => 'google-import', 
				:title => "Import Google Calendar Events"  %> <br/> <br/>
				<h4>Unhappy?</h4> 
				<p><%= button_to "Cancel my account", registration_path(@user), :confirm => 
					"Are you sure?", :method => :delete, :class=>'btn btn-danger' %></p>
			</div>
		</div>
	</div>
	<div class = 'span4' style = 'height:450px;overflow:auto'>
		<table class ='table well' id='center-well'>
			<tr><b>Your Pending Events:</b></tr>
				<% if @user.invited_events.count > 0 %>
					<% @user.invited_events.each do |event| %>
					<tr>
						<td><%= event.title %></td>
						<td><%= event.start_at %></td>
						<td><%= event.end_at %></td>
					</tr>
					<% end %>
				<% else %>
				<tr>
					<td>
						<h3>
							<center>Looks like you're staying home this Friday night. Bobo can help you
							<%= link_to "Find something to do", 'findevent#path', :class => 'btn btn-primary'%>
							</center></h3>
					</td>
				</tr>
				<% end %>
		</table>
	</div>
</div>