config/routes.rb
WebCal::Application.routes.draw do
  resources :timeperiods

  match '/calendars(/:year(/:month))' => 'calendars#index', 
  :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :calendars
  resources :alternatives
  
  match 'users/profile' => 'users#profile', :as=>:user_profile
  match 'users/find_friends' => 'users#find_friends', :as => :user_find_friends
  match 'users/find_events' => 'users#find_events', :as => :user_find_events
  match 'users/friends' => 'users#friends', :as => :user_friends
  
  resources :friendships do
	collection do
		get :friend_requests, :users_list
		post :approve, :ignore, :users_list
  	end
  end
  
  resources :events do
    collection do
      get :invite_friend, :show_calendar
      post :add_timeperiods
    end
  end

  resources :posts

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
                                      :registrations => 'registrations',
                                      :sessions => 'sessions'}

  root :to => 'friendships#users_list' 

end

app/models/event.rb
class Event < ActiveRecord::Base
  validate :title, :presence => true
  
  has_event_calendar

  has_and_belongs_to_many :calendars
  has_and_belongs_to_many :posts
  has_many :timeperiods, :dependent => :destroy
    
  belongs_to :user
  
  has_and_belongs_to_many :invited_users, :class_name => "User"
  has_and_belongs_to_many :admin_users, :class_name => "User", :conditions => "admin_user = true"
  
  attr_accessible :id, :calendar_ids, :end_at, :start_at, :title, :user_id, :invited_users,
  :startDate, :startHour, :endDate, :endHour, :google_id, :location
  
  attr_accessor :startDate, :startHour, :endDate, :endHour
  
  # add some callbacks
  after_initialize :get_datetimes # convert db format to accessors
  before_validation :set_datetimes # convert accessors back to db format

  def get_datetimes
    self.start_at ||= Time.now
    self.end_at ||= Time.now  # if the published_at time is not set, set it to now

    self.startDate ||= self.start_at.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.startHour ||= "#{'%02d' % self.start_at.hour}:#{'%02d' % self.start_at.min}" # extract the time
    
    self.endDate ||= self.end_at.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.endHour ||= "#{'%02d' % self.end_at.hour}:#{'%02d' % self.end_at.min}" # extract the time
  end

  def set_datetimes
    self.start_at = "#{self.startDate} #{self.startHour}:00" # convert the two fields back to db
    self.end_at = "#{self.endDate} #{self.endHour}:00"
  end  

  #methods for adding invited users
  
  def self.add_invited_user(event_id, user_id)
    event = Event.find(event_id)
    user = User.find(user_id)
    unless event.invited_users.include?(user)
      event.invited_users.push(user)
      event.save
    end      
  end  
  
  def self.delete_invited_user(event_id, user_id)
    event = Event.find(event_id)
    user = User.find(user_id)
    event.invited_users.delete(user)
    event.save 
  end
  
  #methods for adding admin users to the event
  def self.add_admin_user(event_id, user_id)
    event = Event.find(event_id)
    user = User.find(user_id)
    unless event.admin_users.include?(user)
      event.invited_users.delete(user)
      event.admin_users.push(user)
      event.save
    end    
  end
  
  def self.delete_admin_user(event_id, user_id)
    event = Event.find(event_id)
    user = User.find(user_id)
    event.admin_users.delete(user)
    event.save  
  end
  
  def find_calendar(calendar_id)
    self.calendar_id = calendar_id
  end
  
  def in_calendar?(calendar)
    return !(calendar.event.where(:id => self.id) == [])
  end
  
  def self.save_to_google_calendar(event_id, user_id)
    user = User.find(user_id)
        
    oauth_yaml = YAML.load_file('.google-api.yaml')
    client = Google::APIClient.new
    client.authorization.client_id = oauth_yaml["client_id"]
    client.authorization.client_secret = oauth_yaml["client_secret"]
    client.authorization.scope = oauth_yaml["scope"]
    client.authorization.refresh_token = user.refresh_token
    client.authorization.access_token = user.token
    
    if client.authorization.refresh_token && client.authorization.expired?
      client.authorization.fetch_access_token!
    end
    
    event = Event.find(event_id)

    #form the attendees array to invite users to gcal event
    attendees = Array.new
    event.invited_users.each do |u|
      attendees.push("email" => "#{u.email}")
    end
    logger.info attendees    
    
    #form the body of the request to post to google
    event_string = {
    'summary' => event.title,
    'location' => event.location,
    'start' => {
      'dateTime' => event.start_at
      },
    'end' => {
      'dateTime' => event.end_at
      },
    'attendees' => attendees
    }
    
    begin
      logger.info JSON(event_string)
      
      service = client.discovered_api('calendar', 'v3')
      res = client.execute(:api_method => service.events.insert,
                      :parameters => {'calendarId' => 'primary'},
                      :headers => {'Content-Type' => 'application/json'},
                      :body => [JSON.dump(event_string)]
                      )
                      

      logger.info res.data.id
      
      event.google_id = res.data.id
      event.save
   rescue Exception => e
     logger.info e.message
     return
   end
  end
    
  def self.delete_from_google_calendar(event_id, user_id)
    user = User.find(user_id)
    
    oauth_yaml = YAML.load_file('.google-api.yaml')
    client = Google::APIClient.new
    client.authorization.client_id = oauth_yaml["client_id"]
    client.authorization.client_secret = oauth_yaml["client_secret"]
    client.authorization.scope = oauth_yaml["scope"]
    client.authorization.refresh_token = user.refresh_token
    client.authorization.access_token = user.token
    
    if client.authorization.refresh_token && client.authorization.expired?
      client.authorization.fetch_access_token!
    end
    
    event = Event.find(event_id)

    begin
      service = client.discovered_api('calendar', 'v3')
      res = client.execute(:api_method => service.events.delete,
                      :parameters => {'calendarId' => 'primary', 'eventId' => event.google_id})
                      
      logger.info "123123123"
   rescue Exception => e
     logger.info e.message
    end
  end
  
  def self.update_google_calendar(event_id, user_id)
    user = User.find(user_id)
    
    oauth_yaml = YAML.load_file('.google-api.yaml')
    client = Google::APIClient.new
    client.authorization.client_id = oauth_yaml["client_id"]
    client.authorization.client_secret = oauth_yaml["client_secret"]
    client.authorization.scope = oauth_yaml["scope"]
    client.authorization.refresh_token = user.refresh_token
    client.authorization.access_token = user.token
    
    if client.authorization.refresh_token && client.authorization.expired?
      client.authorization.fetch_access_token!
    end
    
    event = Event.find(event_id)
    #form the attendees array to invite users to gcal event
    attendees = Array.new
    event.invited_users.each do |u|
      attendees.push("email" => "#{u.email}")
    end
    logger.info attendees    
    
    #form the body of the request to post to google
    event_string = {
    'summary' => event.title,
    'location' => event.location,
    'start' => {
      'dateTime' => event.start_at
      },
    'end' => {
      'dateTime' => event.end_at
      },
    'attendees' => attendees
    }
    
    begin
      service = client.discovered_api('calendar', 'v3')
      res = client.execute(:api_method => service.events.update,
                      :parameters => {'calendarId' => 'primary', 'eventId' => event.google_id},
                      :headers => {'Content-Type' => 'application/json'},
                      :body => [JSON.dump(event_string)]
                      )
                      
      logger.info "123123123"
   rescue Exception => e
     logger.info e.message
    end  
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  before_filter :authenticate_user!, :check_correct_user!
  before_filter :user_owns_event!, :only => [:destroy, :invite_friend]
  
  def user_owns_event!
    if params[:id]
      @event = Event.find(params[:id])
      unless @event.user == current_user
        flash[:warning] = "You don't own that event!"
        redirect_to edit_event_path(@event)
      end
    else
    flash[:warning] = "You don't own that event!"
    redirect_to events_path
    end
  end
  
  def check_correct_user!
    if params[:id]
      @event = Event.find(params[:id])
      unless @event.invited_users.include?(current_user) || @event.user_id == current_user.id
        flash[:warning] = "You're not invited to that event :("
        redirect_to events_path
      end
    end
  end
  
  def index
    if user_signed_in?
      @my_events = Event.where(:user_id => 
      current_user.id).order("start_at")
      @invited_events = Array.new
      
      current_user.invited_events.each do |event|
        @invited_events.push(event)
      end
      
      if @invited_events != []
        @my_events.each do |event|
          @invited_events.delete(event)
        end
      end
    else
      @events = Event.where(:user_id =>
      nil)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    #for calendar display
    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month, :conditions => ['user_id = ?', current_user.id])
    
    
    @event = Event.find(params[:id])
    @calendar = Calendar.find(@event.calendar_ids)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end
  
  def add_timeperiods
    @timeperiod = Timeperiod.new
    @timeperiod.user = current_user
    @timeperiod.save
    
    @event = Event.find(params[:event])
    @event.timeperiods.push(@timeperiod)
    
    respond_to do |format|
      format.js {render :layout => false}
    end
  end
  
  def invite_friend     
    if params[:name]
      @name = params[:name]
      friends = User.search_friends(@name.downcase, current_user.id)
    else 
      friends = current_user.friends
    end

    if params[:event] != nil
      @event = Event.find(params[:event])
    end
    
    @previous_page = true
    @next_page = true
    
    @totalnum = friends.count/25
    
    if params[:page].to_i() > 0
      @page_num = params[:page].to_i()
    else
      @page_num = 0
      @previous_page = false
    end
        
    if @page_num >= @totalnum
      @page_num = @totalnum
      @next_page = false
    end
    
    if friends.first
      @friends = friends[@page_num*25..(@page_num+1)*24] 
    else
      @friends = []
    end
    
    if params[:path] == "true"
      Event.add_invited_user(params[:event], params[:user])
    elsif params[:path] == "false"
      Event.delete_invited_user(params[:event], params[:user])
    elsif params[:path] == "admin add"
      Event.add_admin_user(params[:event], params[:user])
    elsif params[:path] == "admin remove"
      Event.delete_admin_user(params[:event], params[:user])
    end
    
    respond_to do |format|
      format.json {render :json => @event.invited_users}
      format.js { render :layout => false}
    end
        
  end

  # GET /events/new
  # GET /events/new.json
  def new    
    @event = Event.new(params[:event])
    @event.user = current_user
    @event.save
    
    Event.save_to_google_calendar(@event.id, current_user.id)
    
    redirect_to edit_event_path(:id => @event.id)
  end

  # GET /events/1/edit
  def edit
    #for calendar display
    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month, :conditions => ['user_id = ?', current_user.id])
    
    #for timeperiod selection
    @timeperiod = Timeperiod.new
    
    @event = Event.find(params[:id])
    
  end

  # POST /events
  # POST /events.json
  def create
    @calendar = Calendar.all
    @event = Event.new(params[:event])
    @event.user_id = current_user.id
    
      respond_to do |format|
          if @event.save
          
            #call google api client to save event
            Event.save_to_google_calendar(@event.id, current_user.id)
            
            format.html { redirect_to @event, :notice => 'Calendar event was successfully created.' }
            format.json { render :json => @event, :status => :created, :location => @event }
          else
            format.html { redirect_to :notice => 'Conflicting Event Times'}
            format.json { render :json => @event.errors, :status => :unprocessable_entity }
          end
            format.html { redirect_to :notice => 'Conflicting Event Times'}
            format.json { render :json => @event.errors, :status => :unprocessable_entity }
     end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    @calendar = Calendar.where(:user_id => 
    current_user.id)
    unless @event.user_id
      @event.user_id = current_user.id  
    end
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
          Event.update_google_calendar(@event.id, current_user.id)
      
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    Event.delete_from_google_calendar(@event.id, current_user.id)
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  #GET /
  def show_calendar
    respond_to do |format|
       format.js { render :layout => false}
    end
  end
  
  # POST /mobileCreate
  def mobileCreate
    event = Event.new
    event.calendar = params[:calendars]
    event.startTime = params[:startTime]
    event.endTime = params[:endTime]
    event.save
        respond_to do |format|
        if @event.fits?
          if @event.save
            format.html { redirect_to @event, :notice => 'Calendar event was successfully created.' }
            format.json { render :json => @event, :status => :created, :location => @event }
          else
            format.html { redirect_to :notice => 'Conflicting Event Times'}
            format.json { render :json => @event.errors, :status => :unprocessable_entity }
          end
        else
            format.html { redirect_to :notice => 'Conflicting Event Times'}
            format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
<div class = 'container-fluid'>
	<div class="span6">
		<h4>Event name</h4>
		<%= f.text_field :title %>
	</div>
	<div class = 'span6'>
		<h4>Event location</h4>
		<%= f.text_field :location %>
	</div>
</div>
<h4>My event begins promptly at:</h4>
<div class = 'container-fluid'>
	<div class = 'span6'>
		<em>(yyyy/mm/dd)</em> <br/>
		<%= f.text_field :startDate, :class => 'datepicker', :size => 10, :maxlength => 10 %> 
	</div>
	<div class = 'span6'>
		<em>(hours:minutes)</em> <br/>
		<%= f.text_field :startHour, :size => 5, :maxlength => 5 %>
	</div>
</div>

<h4>When do I expect my event to end?</h4>
<div class = 'container-fluid'>
	<div class = 'span6'>
		<%= f.text_field :endDate, :class => 'datepicker', :size => 10, :maxlength => 10 %> 
	</div>
	<div class = 'span6'>
		<%= f.text_field :endHour, :size => 5, :maxlength => 5 %>
	</div>
	<form action = "/events">
    <input type = "submit" class = 'btn btn-success' value = "Plan my event" />
    </form>
</div>

<% end %>

<div class = 'container-fluid thumbnails'>
	<div class = 'span12 thumbnail'>
		<center>
		<%= link_to "Add a time when you're free", add_timeperiods_events_path(:event => @event), :remote => true, :class=>'btn',
:method => :post %>
		</center>
	</div>
</div>
<div class = 'container-fluid thumbnails'>
	<div class = 'span6 thumbnail' id='timeperiods-div'>
	</div>
	<div class = 'span6 thumbnail' id ='timelisting-div' style='max-height:250px;overflow:auto'>
		<% if @event.timeperiods.count > 0 %>	
			<%= render :partial=>'timelisting', :locals => {:times => @event.timeperiods} %>
		<% end %>
	</div>
</div>

app/views/events/_invite_list.html.erb
<h4>
	<% if @event %> 
		<%= @event.invited_users.count%> 
		<% if @event.invited_users.count == 1 %> 
			Friend
		<% else %>
			Friends 
		<% end %> 
		currently invited to this event:</h4>
	<% end %>
<div class = 'thumbnail'>
	<% if @event %>
		<% @event.invited_users.each do |user| %>
			<div class = 'thumbnails'>
				<td><b><%= user.name %></b></td>
				<td><%= image_tag(user.image_url, :class => 'span4')%>
					<% unless user.id == @event.user_id %>
						<%= button_to "Uninvite", invite_friend_events_path(:event => @event, :user =>user.id,:path=>false),
						:remote => true, :method => "get", :class => 'btn btn-warning'%>
						<% if @event.admin_users.include?(user) 
							button_title = "Remove Admin" 
							button_class = "btn btn-warning"
							path = "admin remove" 
						   else
						   	button_title = "Make Admin"
						   	button_class = "btn btn-primary" 
						   	path = "admin add" %>
						<% end %>					
					<% end %>
				</td>
				<br/>
			</div>
		<% end %>
	<% end %>
</div>

app/views/events/_timelisting.html.erb
<table class = 'table'>
	<tr>
		<th>Time</th>
		<th>Friend</th>
	</tr>
<% times.each do |timelisting| %>
  <tr>
    <td><%= timelisting.startHour %> to <%= timelisting.endHour %></td>
    <td><%= User.find(timelisting.user_id).name %></td>
    <% if timelisting.user_id == current_user.id %>
	    <td><%= link_to "Delete", timelisting,
	    	 :method => :delete, :remote => true, :class => 'btn' %></td>
	<% end %>
  </tr>
<% end %>
</table>

app/views/events/add_timeperiods.js.erb
$('#timeperiods-div').html("<%= escape_javascript(render(:partial=>"timeperiods/form")) %>");
$('#timelisting-div').html("<%= escape_javascript(render(:partial=>"timelisting",
											:locals => {:times => @event.timeperiods} )) %>");

app/views/events/edit.html.erb
<div class = 'container-fluid'>
	<div class = 'span8'>
		<%= render 'form' %>
		<div id = 'show-calendar'>
			<%= render 'calendars/form' %>
		</div>
	</div>

	<div class = 'span4'>
		<% if @event.invited_users.include?(current_user) %>
			<div>
				<%= link_to "Invite more friends! Or uninvite some less good friends!", 
				user_friends_path(:event => @event.id), {:style=>'color:#FFFFFF;',
				:class => 'btn btn-primary', :method => 'post'} %>
			</div>
		<% end %>
		
		<br/>
		
		<div id = 'update-div' style="height:540px;overflow:auto">
			<%= render 'events/invite_list' %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<center><h4><%= link_to "Get your Google Calendar events", omniauth_authorize_path(current_user, 'google_oauth2'),
		:class => 'zocial googleplus', :method => :post, :id => 'google-import', 
		:title => "Import Google Events"  %></h4><center>

		<br/>

<div class = 'container-fluid'>
	<div class = 'span6'>		
		<h4>Events you've been invited to:</h4>
	</div>
	<div class = 'span6'>
		<h4>Your Events:</h4>
	</div>
</div>
<div class = 'container-fluid'>
	<div class = 'span6' style = "height:450px;overflow:auto">
		<table class = 'table'>
		  <tr>
		  	<th>Event</th>
		  	<th>Host</th>
		    <th>Begins</th>
		    <th>Ends</th>
		    <th></th>
		    <th></th>
		  </tr>
		
		<% @invited_events.each do |event| %>
		  <tr>
		  	<td id='event-title'><%= event.title %></td>
		  	<td><%= User.find(event.user_id).name %></td>
		    <td><%= event.startDate%> at <%= event.startHour %></td>
		    <td><%= event.endDate%> at <%= event.endHour %></td>
		    <td><%= link_to 'Look at it', edit_event_path(event), :class => 'btn' %></td>
		  </tr>
		<% end %>
		</table>
	</div>
	<div class='span6' style="height:450px;overflow:auto">
		<table class ='table'>
		<tr>
			<th>Event</th>
			<th>Begins</th>
			<th>Ends</th>
		</tr>	
		<% @my_events.each do |event| %>
		<tr>
		  	<td id ='event-title'><%= event.title %></td>
		    <td><%= event.startDate%> at <%= event.startHour %></td>
		    <td><%= event.endDate%> at <%= event.endHour %></td>
		    <td><%= link_to 'Fix it up', edit_event_path(event), :class => 'btn' %>
		    <%= button_to 'Cancel this event', event, :confirm => 'Are you sure?', 
		    :method => :delete, :class => 'btn btn-danger' %></td>
		  </tr>
		<% end %>
		</table>
	</div>
</div>
		
		<br />
		<br />
		<p>
			<%= button_to 'Create a new event', new_event_path, :class => 'btn btn-primary', :method => 'get' %>
		</p>	

app/views/events/invite_friend.js.erb
$('#friend-div').html("<%= escape_javascript(render(:partial=>"users/friends")) %>");
$('#update-div').html("<%= escape_javascript(render(:partial => "invite_list")) %>");
$('#friend-search').html("<%= escape_javascript(render(:partial => "users/friend_search"))%>");

app/views/events/new.html.erb
<div class = 'container-fluid'>
	<div class = 'span8'>
		<%= render 'form' %>
		<div id = 'show-calendar'>
			<%= render 'calendars/form' %>
		</div>
	</div>

	<div class = 'span4'>
		<div>
			<%= link_to "Invite more friends! Or uninvite some less good friends!", 
			user_friends_path(:event => @event.id), {:style=>'color:#00FFFFF;',
			:class => 'btn btn-primary', :method => 'post'} %>
		</div>
		
		<br/>
		
		<div id = 'update-div' style="height:540px;overflow:auto">
			<%= render 'events/invite_list' %>
		</div>
		
		<%= link_to "Back to My Events", events_path, :class => 'btn'%>
	</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class = 'container-fluid'>
	<div class = 'span8'>
		<table class = 'table table-striped'>
			<tr>
				<th>Title</th>
				<th>Location</th>
				<th>Starts</th>
				<th>Ends</th>
			</tr>
			<tr>
				<td><%= @event.title %></td>
				<td><%= @event.location %></td>
			  	<td><%= @event.start_at %></td>
			  	<td><%= @event.end_at %></td>
		  	</tr>
		</table>
		<%= render 'calendars/form' %>
	</div>
	<div class = 'span4'>
		<div id = 'update-div' style="height:540px;overflow:auto">
			<%= render 'events/invite_list' %>
		</div>
	</div>
</div>

app/views/events/show_calendar.js.erb
$('#show-calendar').html("<%= escape_javascript(render(:partial => "calendars/form", 
:locals => {:month => @month, :year => @year, :shown_month => @shown_month, :event_strips => @event_strips}))%>");