config/routes.rb
WebCal::Application.routes.draw do
  resources :timeperiods

  match '/calendars(/:year(/:month))' => 'calendars#index', 
  :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :calendars
  resources :alternatives
  
  match 'users/profile' => 'users#profile', :as=>:user_profile
  match 'users/find_friends' => 'users#find_friends', :as => :user_find_friends
  match 'users/find_events' => 'users#find_events', :as => :user_find_events
  match 'users/friends' => 'users#friends', :as => :user_friends
  
  resources :friendships do
	collection do
		get :friend_requests, :users_list
		post :approve, :ignore, :users_list
  	end
  end
  
  resources :events do
    collection do
      get :invite_friend, :show_calendar
      post :add_timeperiods
    end
  end

  resources :posts

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
                                      :registrations => 'registrations',
                                      :sessions => 'sessions'}

  root :to => 'friendships#users_list' 

end

app/models/timeperiod.rb
class Timeperiod < ActiveRecord::Base
  attr_accessible :time, :user_id, :startDate, :startHour, :endDate, :endHour, :start_at, :end_at
  
  belongs_to :user
  belongs_to :event

  attr_accessor :startDate, :startHour, :endDate, :endHour
  
  # add some callbacks
  after_initialize :get_datetimes # convert db format to accessors
  before_validation :set_datetimes # convert accessors back to db format

  def get_datetimes
    self.start_at ||= Time.now
    self.end_at ||= Time.now  # if the published_at time is not set, set it to now

    self.startDate ||= self.start_at.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.startHour ||= "#{'%02d' % self.start_at.hour}:#{'%02d' % self.start_at.min}" # extract the time
    
    self.endDate ||= self.end_at.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.endHour ||= "#{'%02d' % self.end_at.hour}:#{'%02d' % self.end_at.min}" # extract the time
  end

  def set_datetimes
    self.start_at = "#{self.startDate} #{self.startHour}:00" # convert the two fields back to db
    self.end_at = "#{self.endDate} #{self.endHour}:00"
  end  

end

app/controllers/timeperiods_controller.rb
class TimeperiodsController < ApplicationController
  before_filter lambda{user_owns_this}, :except => :new
  
  def user_owns_this
    if params[:id]
      @timeperiod = Timeperiod.find(params[:id])
      if @timeperiod
        unless @timeperiod.user == current_user
          redirect_to new_timeperiods_path
        end
      end
    end
  end
  
  # GET /timeperiods
  # GET /timeperiods.json
  def index
    @timeperiods = Timeperiod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @timeperiods }
    end
  end

  # GET /timeperiods/1
  # GET /timeperiods/1.json
  def show
    @timeperiod = Timeperiod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @timeperiod }
    end
  end

  # GET /timeperiods/new
  # GET /timeperiods/new.json
  def new
    @timeperiod = Timeperiod.new(params[:timeperiod])

    respond_to do |format|
      format.js {render :layout=>false}
    end
  end

  # GET /timeperiods/1/edit
  def edit
    @timeperiod = Timeperiod.find(params[:id])
    if @timeperiod.user_id != current_user.id
      redirect_to events_path, :flash => {:warning => "Not yours to edit."}
    end
  end

  # POST /timeperiods
  # POST /timeperiods.json
  def create
    
    @timeperiod = Timeperiod.new(params[:timeperiod])

    respond_to do |format|
      if @timeperiod.save
        format.html { redirect_to @timeperiod, :notice => 'Timeperiod was successfully created.' }
        format.json { render :json => @timeperiod, :status => :created, :location => @timeperiod }
      else
        format.html { render :action => "new" }
        format.json { render :json => @timeperiod.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /timeperiods/1
  # PUT /timeperiods/1.json
  def update
    @event = @timeperiod.event
    @timeperiod = Timeperiod.find(params[:id])

    respond_to do |format|
      if @timeperiod.update_attributes(params[:timeperiod])
        format.js {render :layout => false}
        format.html { redirect_to @timeperiod, :notice => 'Timeperiod was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @timeperiod.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /timeperiods/1
  # DELETE /timeperiods/1.json
  def destroy
    @event = @timeperiod.event
    @timeperiod = Timeperiod.find(params[:id])
    @timeperiod.destroy


    respond_to do |format|
      format.js {render :layout => false}
      format.html { redirect_to timeperiods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timeperiods_helper.rb
module TimeperiodsHelper
end

app/views/timeperiods/_form.html.erb
<%= form_for(@timeperiod, :remote => true) do |f| %>
  <% if @timeperiod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeperiod.errors.count, "error") %> prohibited this timeperiod from being saved:</h2>

      <ul>
      <% @timeperiod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = 'container-fluid'>
	<div class = 'span6'>
		<em>(yyyy/mm/dd)</em> <br/>
		<%= f.text_field :startDate, :class => 'datepicker', :size => 10, :maxlength => 10 %> 
	</div>
	<div class = 'span6'>
		<em>(hours:minutes)</em> <br/>
		<%= f.text_field :startHour, :size => 5, :maxlength => 5, :id => 'timeperiod-field' %>
	</div>
</div>
<div class = 'container-fluid'>
	<div class = 'span6'>
		<%= f.text_field :endDate, :class => 'datepicker', :size => 10, :maxlength => 10%> 
	</div>
	<div class = 'span6'>
		<%= f.text_field :endHour, :size => 5, :maxlength => 5 , :id => 'timeperiod-field'%>
	</div>
</div>

  	<form action = "/timeperiods">
    <input type = "submit" class = 'btn btn-success' value = "Submit new time" data-remote="true"/>
    </form>

<%= link_to "Delete this time", @timeperiod, :method => :delete, :remote => :true, :class => 'btn'%>
<% end %>

app/views/timeperiods/destroy.js.erb
$('#timeperiods-div').html("");

app/views/timeperiods/edit.html.erb
<h1>Editing timeperiod</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeperiod %> |
<%= link_to 'Back', timeperiods_path %>

app/views/timeperiods/index.html.erb
<h1>Listing timeperiods</h1>

<table>
  <tr>
    <th>Time</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @timeperiods.each do |timeperiod| %>
  <tr>
    <td><%= timeperiod.time %></td>
    <td><%= timeperiod.user_id %></td>
    <td><%= link_to 'Show', timeperiod %></td>
    <td><%= link_to 'Edit', edit_timeperiod_path(timeperiod) %></td>
    <td><%= link_to 'Destroy', timeperiod, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Timeperiod', new_timeperiod_path %>

app/views/timeperiods/new.html.erb
<h1>New timeperiod</h1>

<%= render 'form' %>

<%= link_to 'Back', timeperiods_path %>

app/views/timeperiods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @timeperiod.time %>
</p>

<p>
  <b>User:</b>
  <%= @timeperiod.user_id %>
</p>


<%= link_to 'Edit', edit_timeperiod_path(@timeperiod) %> |
<%= link_to 'Back', timeperiods_path %>

app/views/timeperiods/update.js.erb
$('#timeperiods-div').html("");
$('#timelisting-div').html("<%= escape_javascript(render(:partial=>"events/timelisting",
											:locals => {:times => @event.timeperiods} )) %>");