config/routes.rb
WebCal::Application.routes.draw do
  resources :timeperiods

  match '/calendars(/:year(/:month))' => 'calendars#index', 
  :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :calendars
  resources :alternatives
  
  match 'users/profile' => 'users#profile', :as=>:user_profile
  match 'users/find_friends' => 'users#find_friends', :as => :user_find_friends
  match 'users/find_events' => 'users#find_events', :as => :user_find_events
  match 'users/friends' => 'users#friends', :as => :user_friends
  
  resources :friendships do
	collection do
		get :friend_requests, :users_list
		post :approve, :ignore, :users_list
  	end
  end
  
  resources :events do
    collection do
      get :invite_friend, :show_calendar
      post :add_timeperiods
    end
  end

  resources :posts

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks",
                                      :registrations => 'registrations',
                                      :sessions => 'sessions'}

  root :to => 'friendships#users_list' 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="http://fonts.googleapis.com/css?family=Schoolbell" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" />
  <script src = "http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js"></script>
  <title>BoboCal: Bobo helps you plan all your social events</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '162666563867675', // App ID
      channelUrl : 'http://evening-frost-9411.herokuapp.com/channel.html', // Channel File
      frictionlessRequests : true
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=162666563867675";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
	<%= image_tag('BoboLogo.png', :size => "120x100", :style=>"display:inline;max-width:200px;float:left")%>
	<div class = 'navbar'>
		<div class ='navbar-inner'>
				<div class = 'container'>
						<ul class = 'nav'>
							<div class="g-plusone" data-href="http://www.BoboCal.com"></div>
						  	<div class="fb-like" data-href="http://www.BoboCal.com" data-colorscheme="dark"
			  				data-send="true" data-width="300" data-show-faces="true" data-font="verdana" id = 'fb-like'></div>
		  				</ul>
				<ul class= 'nav'>					
		  				
					<% if user_signed_in? %>
			  			<h5>Signed in as <%= current_user.email %>. Not you?</h5>
			  			<%= image_tag('TextLogo320100.png', :class => 'span2') %>	
			  			<li><%= button_to  "Sign out", destroy_user_session_path, :method => "delete", :class => 'btn btn-mini'%></li>
			  			
			  			<li><%=button_to "My Profile", user_profile_path(:id => current_user), :class=>'btn btn-mini'%></li>
	
					<% else %>
					
					  <%= link_to "Sign up", new_user_registration_path, 
					  :method => :get, :class => 'btn' %> or
					  <%= link_to "Sign in", new_user_session_path, :class => 'btn' %>
					  	
					   <br/>
					  
				    	<%= link_to "Sign in with Facebook", omniauth_authorize_path(resource_name, 'facebook'),
				    	:class => 'zocial facebook', :method => :post %>
				    	<%= link_to "Sign in with Google", omniauth_authorize_path(resource_name, 'google_oauth2'),
				    	:class => 'zocial googleplus', :method => :post%>
			    			    	
					<% end %>		  				
		  				
			  		<% if user_signed_in? %>
			  			<% if current_user.has_requests? %>
			  				<li class = 'btn'><%= link_to "Friend Requests", 
			  				friend_requests_friendships_path , :method => "get" %></li>
			    		<% end %>
		  			<% end %>
		  		</ul>
  			</div>
  		</div>
  	</div>
  	<div class = 'container-fluid'>
  		<div class = 'row-fluid'>
	  		<div class = 'span2'>
		  		<div class = 'well sidebar-nav' id = 'center-well'>
					<ul class = 'nav nav-list'>
						<li>Bobo Manager</li>
						<li class = 'divider'></li>
						<li><%= link_to "Users", users_list_friendships_path, :method => "get", :class => 'btn' %></li>
						</br>
						<li><%= link_to "Friends", user_friends_path, :method => 'get', :class => 'btn' %></li>
						</br>
						<li><%= link_to "Events", events_path, :method => 'get', :class => 'btn' %></li>
						</br>
						<li><%= link_to "Calendar", calendars_path, :method => 'get', :class => 'btn'%></li>
					</ul>
				</div>
				<div class = 'thumbnail'>
					<div class = 'thumbnail'>
						Bobo Helper
					</div>
					<center><%= link_to "Getting started with BoboCal", 
					alternatives_path, :class => 'btn btn-inverse',:id => 'getting-started'%></center>
					<center><%= link_to "Making an event with BoboCal", 
					new_alternative_path, :class => 'btn btn-inverse',:id => 'making-event'%></center>									</div>
		  		</div>
			<div class = 'span10' >
				<% if flash[:warning]%>
					<div class = 'well' id='flash-warning'><h3><%= flash[:warning]%></h3></div>
				<% end %>
				
				<div class = 'hero-unit' id ='center-hero-unit'>						
						<center>
							<% if current_user %>
								<% if @event %>
									<p>Bobo is currently planning <%= @event.title %> <br/>				
										<%= link_to 'Change of plans, cancel my event.', @event, 
										 {:style => 'color:#FFFFFF', :confirm => 'Are you sure you want to cancel ' +@event.title+'?', 
										 :method => :delete, :class => 'btn btn-danger'} %>
										 
										<%= link_to 'Continue planning, Bobo', edit_event_path(@event),
										{:style=>'color:#FFFFFF',:class => 'btn btn-inverse'}%>
									</p>
								<% else %>
									<p>Bobo isn't planning an event right now!
									<%= button_to 'Enlist Bobo', new_event_path, :class => 'btn btn-primary', :method => 'get' %>
									</p>
								<% end %>
							<% end %>
						</center>	
					<%= yield %>
				</div>
			</div>
		</div>
	</div>
	  <footer>
        <p>&copy; BoboCal 2012. Created by <%= link_to "Boyang Niu", "http://www.boyangniu.com/", :method=>'get' %></p>
      </footer>
</body>
</html>